apiVersion: apps/v1
kind: Deployment
metadata:
  name: lineaje-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lineaje-demo-app
  template:
    metadata:
      labels:
        app: lineaje-demo-app
    spec:
      containers:
        - name: back-end
          image: 522814735753.dkr.ecr.us-east-2.amazonaws.com/lineaje-repo:20250205045928
          ports:
            - containerPort: 8080
          env:
          - name: DOCKER_ENV
            value: "dev"
---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: lineaje-demo
  name: lineaje-demo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: lineaje-demo-app
  sessionAffinity: None
  type: ClusterIP
---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lineaje-demo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: lineaje-demo.lineaje.opsera.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: lineaje-demo
            port:
              number: 8080
